install: true

language: c

before_install:
  # Make sure correct gcc is installed
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-linux-gnueabi make ncurses-dev

script:
  - arm-linux-gnueabi-gcc-4.6 -march=armv6 -marm omxtx.c -o omxtx
  
after_script:
  - file omxtx.c
